columns:
  timestamp: object
  location_name: object
  location_lat: float64
  location_lon: float64
  co: float64
  no2: float64
  o3: float64
  pm10: float64
  pm25: float64
  so2: float64
  aqi: float64

numerical_columns:
  - location_lat
  - location_lon
  - co
  - no2
  - o3
  - pm10
  - pm25
  - so2
  - aqi